"""Deterministic offline LLM backend.

The :class:`MockLLM` produces plausible code and edits with no network access
and no API key. It exists so the whole product -- inline completion, chat,
agentic edit, and the test suite -- runs fully offline. The output is
deterministic for a given prompt so tests can assert on it.

It is *not* a language model. It uses a handful of heuristics that recognise
the prompt shapes produced by :mod:`aiforge.ai` and returns sensible canned
responses (a function body, a code-fenced answer, a unified diff, etc.).
"""
from __future__ import annotations

import hashlib
import re
from typing import Iterator, List

from .base import CompletionRequest, Message


def _last_user(messages: List[Message]) -> str:
    for msg in reversed(messages):
        if msg.role == "user":
            return msg.content
    return ""


def _stream(text: str) -> Iterator[str]:
    """Yield ``text`` in small chunks to exercise the streaming path."""
    # Split on word boundaries, keeping the delimiter, so consumers that join
    # the chunks reconstruct the exact string.
    for chunk in re.findall(r"\S+\s*|\s+", text):
        yield chunk


class MockLLM:
    """Offline, deterministic backend implementing :class:`LLMBackend`."""

    name = "mock"

    def __init__(self, *, model: str = "mock-coder") -> None:
        self.model = model

    # -- public API ---------------------------------------------------------
    def complete(self, request: CompletionRequest) -> Iterator[str]:
        system = (request.system or "").lower()
        user = _last_user(request.messages)

        if "fill-in-the-middle" in system or "<fim_" in user or "complete the code" in system:
            return _stream(self._completion(user))
        if "unified diff" in system or "produce a unified diff" in system:
            return _stream(self._diff(user))
        if "edit" in system and "instruction" in system:
            return _stream(self._edit(user))
        # Default: a chat answer about the codebase.
        return _stream(self._chat(user))

    # -- canned responses ---------------------------------------------------
    def _completion(self, user: str) -> str:
        """Return a fill-in-the-middle body based on the visible prefix."""
        prefix = self._extract(user, "prefix")
        suffix = self._extract(user, "suffix")
        # Heuristic: continue an obvious function or statement.
        last_line = prefix.rstrip().splitlines()[-1] if prefix.strip() else ""
        stripped = last_line.strip()
        if stripped.endswith(":") and ("def " in stripped or "class " in stripped):
            indent = re.match(r"\s*", last_line).group(0) + "    "
            name = re.search(r"def\s+(\w+)", stripped)
            if name:
                return (
                    f"\n{indent}\"\"\"Auto-generated by aiforge MockLLM.\"\"\""
                    f"\n{indent}raise NotImplementedError({name.group(1)!r})"
                )
            return f"\n{indent}pass"
        if stripped.endswith("=") or stripped.endswith("("):
            return " None"
        if "return" in stripped and not stripped.endswith(("return", "return ")):
            return ""
        # Generic continuation that respects the suffix when present.
        if suffix.strip():
            return ""
        return "  # completed by aiforge MockLLM"

    def _chat(self, user: str) -> str:
        digest = hashlib.sha256(user.encode("utf-8")).hexdigest()[:8]
        question = user.strip().splitlines()[0][:120] if user.strip() else "your question"
        return (
            f"Based on the retrieved code context, here is how this works.\n\n"
            f"You asked: \"{question}\"\n\n"
            "The relevant logic is implemented as a small, well-scoped function. "
            "A minimal example:\n\n"
            "```python\n"
            "def example():\n"
            "    \"\"\"Illustrative snippet from the MockLLM backend.\"\"\"\n"
            "    return 42\n"
            "```\n\n"
            f"(deterministic mock answer {digest})"
        )

    def _edit(self, user: str) -> str:
        """Return a full new-file body for an edit instruction."""
        original = self._extract(user, "current content") or self._extract(user, "content")
        if not original:
            return "# aiforge: edited file\n"
        # A deterministic, reviewable transformation: prepend a header comment.
        header = "# Edited by aiforge MockLLM\n"
        if original.startswith(header):
            return original
        return header + original

    def _diff(self, user: str) -> str:
        """Return a tiny but valid unified diff that prepends a comment line."""
        path = self._extract(user, "path") or "file.py"
        original = self._extract(user, "current content") or self._extract(user, "content")
        first_line = original.splitlines()[0] if original.splitlines() else ""
        new_line = "# Edited by aiforge MockLLM"
        return (
            f"--- a/{path}\n"
            f"+++ b/{path}\n"
            "@@ -1,1 +1,2 @@\n"
            f"+{new_line}\n"
            f" {first_line}\n"
        )

    # -- helpers ------------------------------------------------------------
    @staticmethod
    def _extract(text: str, label: str) -> str:
        """Pull a labelled, fenced section out of a prompt.

        Prompts built by :mod:`aiforge.ai` wrap payloads as::

            <label>
            ...content...
            </label>

        We extract the inner content so the mock can echo / transform it.
        """
        pattern = re.compile(
            rf"<{re.escape(label)}>\n?(.*?)</{re.escape(label)}>",
            re.DOTALL | re.IGNORECASE,
        )
        match = pattern.search(text)
        if match:
            return match.group(1)
        return ""
